export const GET_CHARACTERS = "GET_CHARACTERS";
export const CHARACTER_DETAIL = "CHARACTER_DETAIL";
export const UPDATE_INPUT_VALUE = "UPDATE_INPUT_VALUE";
export const SELECT_CHARACTER = "SELECT_CHARACTER";
