const characters = [
  {
    id: 1,
    name: "Rick Sanchez",
    species: "Human",
    gender: "Male",
    image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
  },
  {
    id: 2,
    name: "Morty Smith",
    species: "Human",
    gender: "Male",
    image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
  },
  {
    id: 3,
    name: "Summer Smith",
    species: "Human",
    gender: "Female",
    image: "https://rickandmortyapi.com/api/character/avatar/3.jpeg",
  },
  {
    id: 4,
    name: "Beth Smith",
    species: "Human",
    gender: "Female",
    image: "https://rickandmortyapi.com/api/character/avatar/4.jpeg",
  },
  {
    id: 5,
    name: "Tobias Zapata",
    species: "Capo",
    gender: "☝🤓",
    image: "https://rickandmortyapi.com/api/character/avatar/270.jpeg",
  },
  {
    id: 6,
    name: "Luca Vera",
    species: "Gamer",
    gender: "Ragequiter",
    image: "https://rickandmortyapi.com/api/character/avatar/13.jpeg",
  },
  {
    id: 7,
    name: "Juan Prato",
    species: "Programador",
    gender: "Otaku / No binario",
    image: "https://rickandmortyapi.com/api/character/avatar/25.jpeg",
  },
  {
    id: 8,
    name: "Renzo Rivero",
    species: "Culo Sucio",
    gender: "Suertudo",
    image: "https://rickandmortyapi.com/api/character/avatar/420.jpeg",
  },
  {
    id: 9,
    name: "Agustin Cremonese",
    species: "Tiltmaster",
    gender: "FF",
    image: "https://rickandmortyapi.com/api/character/avatar/67.jpeg",
  },
  {
    id: 10,
    name: "Marco Tangreti",
    species: "Ludópata",
    gender: "Nokosexual",
    image: "https://rickandmortyapi.com/api/character/avatar/459.jpeg",
  },
  {
    id: 11,
    name: "Franco Cejas",
    species: "Bronce",
    gender: "Feeder",
    image: "https://rickandmortyapi.com/api/character/avatar/150.jpeg",
  },
  {
    id: 12,
    name: "Florencia Jolodovsky",
    species: "Hater",
    gender: "JuanGuarnizoLover",
    image: "https://pbs.twimg.com/media/EohqiLuW8AA5yt0.jpg",
  },
  {
    id: 13,
    name: "Santiago Maidana",
    species: "Pollera",
    gender: "Otaku",
    image: "https://rickandmortyapi.com/api/character/avatar/33.jpeg",
  },
  {
    id: 14,
    name: "Leandro Marino",
    species: "Marihuano",
    gender: "Libro De Petete",
    image: "https://rickandmortyapi.com/api/character/avatar/244.jpeg",
  },
  {
    id: 15,
    name: "Ulises Ledesma",
    species: "Cacique",
    gender: "Josepo",
    image: "https://rickandmortyapi.com/api/character/avatar/272.jpeg",
  },
  {
    id: 16,
    name: "Gloria Contreras",
    species: "Disléxica",
    gender: "Otaku De Closet",
    image: "https://rickandmortyapi.com/api/character/avatar/99.jpeg",
  },
  {
    id: 17,
    name: "Ludmila Luna",
    species: "Pollera",
    gender: "Colorada Mufa",
    image: "https://rickandmortyapi.com/api/character/avatar/17.jpeg",
  },
];

export default characters;
